version: '3.1'

services:
  web:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8000:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - USER=Bicadmin
      - PASSWORD=Bicadmin231

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=Bicadmin
      - POSTGRES_PASSWORD=Bicadmin231
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data:

